### ISSUE TITLE
Discrepancy in LiDAR Data Timestamp Calculation Between Datasets

### ISSUE THREAD

**Issue by ljy-zju** [JokerJohn/PALoc#15]
I have noticed a potential issue regarding the timestamp calculation for lidar points in the two datasets.
In the **fs_os128_corridor.yaml** file, the **lidar_type is set to 3**, which means that the **OUST64** lidar type is used, corresponding to the **oust64_handler**. Here, the timestamp for each lidar point is calculated as:

`pt_full.curvature = (i % 2048) / 20480.0 * time_unit_scale;
`

On the other hand, in the **geode_beta_os64.yaml** file, the **lidar_type is set to 8**, which indicates the use of the **OUS128** lidar type and the corresponding **oust128_handler**. In this case, the timestamp for each lidar point is calculated as:

`pt_full.curvature = pl_orig.points[i].t * time_unit_scale;
`

Is this a potential ambiguity?
The discrepancy in timestamp calculation methods seems significant, as the timestamp is crucial for point cloud distortion removal. The different formulas used to compute the timestamp for each lidar point in the two datasets could lead to inconsistent or incorrect results when processing the data.

Could you clarify whether this is intentional or if further adjustments are needed?

**Comment by ljy-zju** [comment]
I discovered this issue because, in my own experiments, I found that for the Ouster128 lidar in the FP dataset, the timestamp difference between the start and end of a lidar frame is 2 * 10^n, whereas for previous lidar models like Livox Avia, Velodyne, Ouster64, and Hesai, the difference is 1 * 10^n. So I first looked into how PAloc handles timestamps for the Ouster128 lidar in the FP dataset and found many mismatches between the code and the configuration described in the comments, as mentioned above.

**Comment by JokerJohn** [comment]
@ljy-zju 
Your observation is correct. The point cloud format in the `FusionPortable` dataset differs slightly from the Ouster official default format, and there is also a difference in the timestamp units. In the annotated code, I output the timestamps for some points to ensure they are correct within the `0-100ms` range. Since the resolution is `2048x128`, with each scan line capturing 2048 points for a full 360-degree rotation, the total time is 0.1s, which allows the calculation of timestamps for each point.

The point cloud resolution in the `FusionPortableV2` dataset is `1024x128`, and its format is consistent with the official Ouster radar standard. Although the `GEODE`/`Newer College` dataset is also compatible with the Ouster LiDAR, it should follow the standard data format and timestamp units. To distinguish it, I processed the `FusionPortable` dataset separately.

**Comment by ljy-zju** [comment]
It’s possible that this dataset has some issues. I observed that the ground truth trajectory provided by the official source even shows fluctuations and jumps during escalator rides.
![image](https://github.com/user-attachments/assets/c558ae43-b17f-4e6f-b97f-4e70fb017270)

**Comment by JokerJohn** [comment]
The ground truth trajectories for these sequences in the `FusionPortable` dataset were generated using the hdl_Localization algorithm, and indeed, the accuracy is limited. We have recently organized the data and will update it with the results from PALoc.

**Comment by ljy-zju** [comment]
I hope we can eventually use the refined ground truth in our latest work. Thank you for your hard work.
